baseURL        = "https://mugijiru.github.io"
languageCode   = "ja-JP"
HasCJKLanguage = true
title          = "麦汁三昧"
theme          = "hello-friend-ng"
paginate       = 20
publishDir     = "docs"

[markup.goldmark.renderer]
    unsafe = true

[params]
    author = "麦汁"
    info = "Emacs を使って Rails アプリケーションを開発している人"
    description = "麦汁の個人サイト"
    keywords = "blog,developer,personal"

    # for hello-frint-ng
    dateform          = "2006年01月02日"
    dateformShort     = "01月02日"
    dateformNum       = "2006年01月02日"
    dateformNumTime   = "2006年01月02日 15:04"

    disableReadOtherPosts = false
    enableSharingButtons  = true
    enableThemeToggle     = true

    homeSubtitle = "麦汁さんの個人サイト"

    enableGitInfo = false

    customCSS = ["/css/amazon.css", "/css/adsense.css"]

    amazonJpAffiliate = "nue06-22"

  [params.logo]
    logoText = "$ cd /home/mugijiru"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/mugijiru"

  [[params.social]]
    name = "github"
    url  = "https://github.com/mugijiru"

  [params.footer]
    rss = true
    lowerText = ["Powered by <a href=\"http://gohugo.io\">Hugo</a>",
                 "Made with &#10084; by <a href=\"https://github.com/rhazdon\">Djordje Atlialp</a>"]
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    identifier = "profile"
    name = "Profile"
    url = "/profile/"
    weight = 2
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 3
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    weight = 4
