name: build and publish

on:
  push:
    paths:
      - 'content/**/*.md'
      - 'config.toml'
      - '.github/workflows/build.yml'
    branches:
      - 'entry/**'
      - 'bump-hugo/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo

      - name: Check diff
        run: |
          git diff --exit-code --quiet || echo 'found_update=1' >> $GITHUB_ENV

      - name: Setup git config
        if: env.found_update == 1
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Commit & Push
        if: env.found_update == 1
        run: |
          git add .
          git commit -m "Build Hugo by GitHub Actions"
          git push

      - name: Notify slack build result
        uses: lazy-actions/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: '*Build*'
          mention: 'here'
          username: 'GitHub Actions'
          mention_if: 'failure'
          channel: '#develop'
          url: ${{ secrets.SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
